on: 
  workflow_dispatch:
    inputs:
      run_step_one:
        description: 'run_step_one???: '     
        required: true
        default: 'false'
        type: boolean
      run_step_two:
        description: 'run_step_one???: '     
        required: true
        default: 'false'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Step One
        if: ${{ github.event.inputs.run_step_one == 'true' }}
        run: echo "Running Step One TRUE! "
      
      - name: Step Two
        if: ${{ github.event.inputs.run_step_two == 'true' }}
        run: echo "Running Step Two"
