on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level (choose one: debug, info, warning, error)'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: Validate log level
      run: |
        case "${{ github.event.inputs.logLevel }}" in
          debug|info|warning|error)
            echo "Log level: ${{ github.event.inputs.logLevel }}"
            ;;
          *)
            echo "Invalid log level: ${{ github.event.inputs.logLevel }}"
            exit 1
            ;;
        esac
    - run: |
        echo "Tags: ${{ github.event.inputs.tags }}"
